# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate minimum distance
#' @description This function calculates the minimum distance between a matrix
#' of locations r and another matrix of locations x
#' @param r A numeric matrix with each row being a pair of coordinates.
#' @param x A numeric matrix with each row being a pair of coordinates.
#' @return A vector with as many elements as rows in r, corresponding to the minimum distance between the rows in r and all the rows in x.
#' @export
#'
calcMinDist_cpp <- function(r, x) {
    .Call(`_vultRmap_calcMinDist_cpp`, r, x)
}

